# Generated by Django 4.2 on 2025-07-31 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-operation_uuid', '-timestamp'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID операции'),
        ),
    ]
