# Generated by Django 4.2 on 2025-07-31 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_options_transaction_operation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменена'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversing_transaction', to='api.transaction', verbose_name='Отменяет транзакцию'),
        ),
    ]
