# Generated by Django 4.2 on 2025-07-31 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_is_cancelled_transaction_reverses'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время операции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания записи'),
        ),
    ]
