# Generated by Django 4.2 on 2025-08-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_operation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reverses',
        ),
    ]
