version: '3.8'

services:
  db:
    image: postgres:13
    container_name: chem_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    # Используем .env из корня
    env_file: .env

  backend:
    build: ./backend
    container_name: chem_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # Используем .env из корня
    env_file: .env
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: chem_frontend_dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data_dev: