version: '3.8'

services:
  db:
    image: postgres:13
    container_name: chem_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    # Точно так же, используем environment
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  backend:
    build: ./backend
    container_name: chem_backend_prod
    
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      - db

volumes:
  postgres_data_prod: