version: '3.8'

services:
  db:
    image: postgres:13
    container_name: chem_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    # Эти переменные нужны, чтобы PostgreSQL создал базу и пользователя
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build: ./backend
    container_name: chem_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # Явно передаем ВСЕ переменные, которые нужны Django
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS} # Не забудьте добавить эту переменную в .env
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: chem_frontend_dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data_dev: