version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file: .env # Берет переменные из .env файла
    # Порт 5432 НЕ выставляем наружу для безопасности

  backend:
    build:
      context: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db

  nginx:
    build: ./nginx # У Nginx будет свой Dockerfile и конфиг
    ports:
      - "80:80" # Открываем наружу только 80 порт
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: